<?php
/**
 * PublicHolidaysApi
 * PHP version 5
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Reference
 *
 * This API allows 3rd party integration of your Float data.
 *
 * OpenAPI spec version: 3.0.0-beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Float\Client\Api;

use \Float\Client\ApiClient;
use \Float\Client\ApiException;
use \Float\Client\Configuration;
use \Float\Client\ObjectSerializer;

/**
 * PublicHolidaysApi Class Doc Comment
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PublicHolidaysApi
{
    /**
     * API Client
     *
     * @var \Float\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Float\Client\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Float\Client\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \Float\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \Float\Client\ApiClient $apiClient set the API client
     *
     * @return PublicHolidaysApi
     */
    public function setApiClient(\Float\Client\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation addHoliday
     *
     * Block out times throughout the year when the office is closed
     *
     * @param \Float\Client\Model\Holiday $holiday The holiday to create (optional)
     * @throws \Float\Client\ApiException on non-2xx response
     * @return \Float\Client\Model\Holiday
     */
    public function addHoliday($holiday = null)
    {
        list($response) = $this->addHolidayWithHttpInfo($holiday);
        return $response;
    }

    /**
     * Operation addHolidayWithHttpInfo
     *
     * Block out times throughout the year when the office is closed
     *
     * @param \Float\Client\Model\Holiday $holiday The holiday to create (optional)
     * @throws \Float\Client\ApiException on non-2xx response
     * @return array of \Float\Client\Model\Holiday, HTTP status code, HTTP response headers (array of strings)
     */
    public function addHolidayWithHttpInfo($holiday = null)
    {
        // parse inputs
        $resourcePath = "/holidays";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json', 'application/xml']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json', 'application/xml']);

        // body params
        $_tempBody = null;
        if (isset($holiday)) {
            $_tempBody = $holiday;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Float\Client\Model\Holiday',
                '/holidays'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Float\Client\Model\Holiday', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Float\Client\Model\Holiday', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation deleteHoliday
     *
     * Delete a holiday
     *
     * @param int $holidayId holiday id to delete (required)
     * @throws \Float\Client\ApiException on non-2xx response
     * @return void
     */
    public function deleteHoliday($holidayId)
    {
        list($response) = $this->deleteHolidayWithHttpInfo($holidayId);
        return $response;
    }

    /**
     * Operation deleteHolidayWithHttpInfo
     *
     * Delete a holiday
     *
     * @param int $holidayId holiday id to delete (required)
     * @throws \Float\Client\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteHolidayWithHttpInfo($holidayId)
    {
        // verify the required parameter 'holidayId' is set
        if ($holidayId === null) {
            throw new \InvalidArgumentException('Missing the required parameter $holidayId when calling deleteHoliday');
        }
        // parse inputs
        $resourcePath = "/holidays/{holiday_id}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json', 'application/xml']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json', 'application/xml']);

        // path params
        if ($holidayId !== null) {
            $resourcePath = str_replace(
                "{" . "holiday_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($holidayId),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/holidays/{holiday_id}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

    /**
     * Operation getHoliday
     *
     * Retrieve a single holiday
     *
     * @param int $holidayId The holiday&#39;s ID (required)
     * @throws \Float\Client\ApiException on non-2xx response
     * @return \Float\Client\Model\Holiday
     */
    public function getHoliday($holidayId)
    {
        list($response) = $this->getHolidayWithHttpInfo($holidayId);
        return $response;
    }

    /**
     * Operation getHolidayWithHttpInfo
     *
     * Retrieve a single holiday
     *
     * @param int $holidayId The holiday&#39;s ID (required)
     * @throws \Float\Client\ApiException on non-2xx response
     * @return array of \Float\Client\Model\Holiday, HTTP status code, HTTP response headers (array of strings)
     */
    public function getHolidayWithHttpInfo($holidayId)
    {
        // verify the required parameter 'holidayId' is set
        if ($holidayId === null) {
            throw new \InvalidArgumentException('Missing the required parameter $holidayId when calling getHoliday');
        }
        // parse inputs
        $resourcePath = "/holidays/{holiday_id}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json', 'application/xml']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json', 'application/xml']);

        // path params
        if ($holidayId !== null) {
            $resourcePath = str_replace(
                "{" . "holiday_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($holidayId),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Float\Client\Model\Holiday',
                '/holidays/{holiday_id}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Float\Client\Model\Holiday', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Float\Client\Model\Holiday', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getHolidays
     *
     * List holidays
     *
     * @throws \Float\Client\ApiException on non-2xx response
     * @return \Float\Client\Model\Holiday[]
     */
    public function getHolidays()
    {
        list($response) = $this->getHolidaysWithHttpInfo();
        return $response;
    }

    /**
     * Operation getHolidaysWithHttpInfo
     *
     * List holidays
     *
     * @throws \Float\Client\ApiException on non-2xx response
     * @return array of \Float\Client\Model\Holiday[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getHolidaysWithHttpInfo()
    {
        // parse inputs
        $resourcePath = "/holidays";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json', 'application/xml']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json', 'application/xml']);


        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Float\Client\Model\Holiday[]',
                '/holidays'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Float\Client\Model\Holiday[]', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Float\Client\Model\Holiday[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation updateHoliday
     *
     * Update a holiday's details
     *
     * @param int $holidayId The holiday&#39;s ID (required)
     * @throws \Float\Client\ApiException on non-2xx response
     * @return \Float\Client\Model\Holiday
     */
    public function updateHoliday($holidayId)
    {
        list($response) = $this->updateHolidayWithHttpInfo($holidayId);
        return $response;
    }

    /**
     * Operation updateHolidayWithHttpInfo
     *
     * Update a holiday's details
     *
     * @param int $holidayId The holiday&#39;s ID (required)
     * @throws \Float\Client\ApiException on non-2xx response
     * @return array of \Float\Client\Model\Holiday, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateHolidayWithHttpInfo($holidayId)
    {
        // verify the required parameter 'holidayId' is set
        if ($holidayId === null) {
            throw new \InvalidArgumentException('Missing the required parameter $holidayId when calling updateHoliday');
        }
        // parse inputs
        $resourcePath = "/holidays/{holiday_id}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json', 'application/xml']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json', 'application/xml']);

        // path params
        if ($holidayId !== null) {
            $resourcePath = str_replace(
                "{" . "holiday_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($holidayId),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PATCH',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Float\Client\Model\Holiday',
                '/holidays/{holiday_id}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Float\Client\Model\Holiday', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Float\Client\Model\Holiday', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
