<?php
/**
 * PersonTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Reference
 *
 * This API allows 3rd party integration of your Float data.
 *
 * OpenAPI spec version: 3.0.0-beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Float\Client;

/**
 * PersonTest Class Doc Comment
 *
 * @category    Class */
// * @description Person
/**
 * @package     Float\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PersonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Person"
     */
    public function testPerson()
    {
    }

    /**
     * Test attribute "peopleId"
     */
    public function testPropertyPeopleId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "jobTitle"
     */
    public function testPropertyJobTitle()
    {
    }

    /**
     * Test attribute "department"
     */
    public function testPropertyDepartment()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "avatarFile"
     */
    public function testPropertyAvatarFile()
    {
    }

    /**
     * Test attribute "autoEmail"
     */
    public function testPropertyAutoEmail()
    {
    }

    /**
     * Test attribute "employeeType"
     */
    public function testPropertyEmployeeType()
    {
    }

    /**
     * Test attribute "nonWorkDays"
     */
    public function testPropertyNonWorkDays()
    {
    }

    /**
     * Test attribute "workDayHours"
     */
    public function testPropertyWorkDayHours()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "contractor"
     */
    public function testPropertyContractor()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "endDate"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {
    }
}
