<?php
/**
 * TimeoffTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Reference
 *
 * This API allows 3rd party integration of your Float data.
 *
 * OpenAPI spec version: 3.0.0-beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Float\Client;

/**
 * TimeoffTest Class Doc Comment
 *
 * @category    Class */
// * @description Timeoff
/**
 * @package     Float\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TimeoffTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Timeoff"
     */
    public function testTimeoff()
    {
    }

    /**
     * Test attribute "timeoffId"
     */
    public function testPropertyTimeoffId()
    {
    }

    /**
     * Test attribute "timeoffTypeId"
     */
    public function testPropertyTimeoffTypeId()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "endDate"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {
    }

    /**
     * Test attribute "timeoffNotes"
     */
    public function testPropertyTimeoffNotes()
    {
    }

    /**
     * Test attribute "modifiedBy"
     */
    public function testPropertyModifiedBy()
    {
    }

    /**
     * Test attribute "createdBy"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {
    }

    /**
     * Test attribute "repeatState"
     */
    public function testPropertyRepeatState()
    {
    }

    /**
     * Test attribute "repeatEnd"
     */
    public function testPropertyRepeatEnd()
    {
    }

    /**
     * Test attribute "fullDay"
     */
    public function testPropertyFullDay()
    {
    }

    /**
     * Test attribute "peopleIds"
     */
    public function testPropertyPeopleIds()
    {
    }
}
