<?php
/**
 * ProjectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Reference
 *
 * This API allows 3rd party integration of your Float data.
 *
 * OpenAPI spec version: 3.0.0-beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Float\Client;

use \Float\Client\Configuration;
use \Float\Client\ApiClient;
use \Float\Client\ApiException;
use \Float\Client\ObjectSerializer;

/**
 * ProjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addProject
     *
     * Add a new project.
     *
     */
    public function testAddProject()
    {
    }

    /**
     * Test case for deleteProject
     *
     * Delete a project.
     *
     */
    public function testDeleteProject()
    {
    }

    /**
     * Test case for getProject
     *
     * Retrieve a single project..
     *
     */
    public function testGetProject()
    {
    }

    /**
     * Test case for getProjects
     *
     * List projects.
     *
     */
    public function testGetProjects()
    {
    }

    /**
     * Test case for updateProject
     *
     * Update a project's details.
     *
     */
    public function testUpdateProject()
    {
    }
}
