<?php
/**
 * PublicHolidaysApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Reference
 *
 * This API allows 3rd party integration of your Float data.
 *
 * OpenAPI spec version: 3.0.0-beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Float\Client;

use \Float\Client\Configuration;
use \Float\Client\ApiClient;
use \Float\Client\ApiException;
use \Float\Client\ObjectSerializer;

/**
 * PublicHolidaysApiTest Class Doc Comment
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PublicHolidaysApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addHoliday
     *
     * Block out times throughout the year when the office is closed.
     *
     */
    public function testAddHoliday()
    {
    }

    /**
     * Test case for deleteHoliday
     *
     * Delete a holiday.
     *
     */
    public function testDeleteHoliday()
    {
    }

    /**
     * Test case for getHoliday
     *
     * Retrieve a single holiday.
     *
     */
    public function testGetHoliday()
    {
    }

    /**
     * Test case for getHolidays
     *
     * List holidays.
     *
     */
    public function testGetHolidays()
    {
    }

    /**
     * Test case for updateHoliday
     *
     * Update a holiday's details.
     *
     */
    public function testUpdateHoliday()
    {
    }
}
