<?php
/**
 * TasksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Reference
 *
 * This API allows 3rd party integration of your Float data.
 *
 * OpenAPI spec version: 3.0.0-beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Float\Client;

use \Float\Client\Configuration;
use \Float\Client\ApiClient;
use \Float\Client\ApiException;
use \Float\Client\ObjectSerializer;

/**
 * TasksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TasksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addTask
     *
     * Add a new task.
     *
     */
    public function testAddTask()
    {
    }

    /**
     * Test case for deleteTask
     *
     * Delete a task.
     *
     */
    public function testDeleteTask()
    {
    }

    /**
     * Test case for getTask
     *
     * Retrieve a single task.
     *
     */
    public function testGetTask()
    {
    }

    /**
     * Test case for getTasks
     *
     * List tasks. This includes any tasks or repeating task sets that start or end within the date range specified..
     *
     */
    public function testGetTasks()
    {
    }

    /**
     * Test case for updateTask
     *
     * Update a task's details.
     *
     */
    public function testUpdateTask()
    {
    }
}
