<?php
/**
 * TimeOffApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Reference
 *
 * This API allows 3rd party integration of your Float data.
 *
 * OpenAPI spec version: 3.0.0-beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Float\Client;

use \Float\Client\Configuration;
use \Float\Client\ApiClient;
use \Float\Client\ApiException;
use \Float\Client\ObjectSerializer;

/**
 * TimeOffApiTest Class Doc Comment
 *
 * @category Class
 * @package  Float\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TimeOffApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addTimeoff
     *
     * Add a new time off.
     *
     */
    public function testAddTimeoff()
    {
    }

    /**
     * Test case for deleteTimeoff
     *
     * Delete a time off record.
     *
     */
    public function testDeleteTimeoff()
    {
    }

    /**
     * Test case for getTimeoff
     *
     * Retrieve a single time off.
     *
     */
    public function testGetTimeoff()
    {
    }

    /**
     * Test case for getTimeoffs
     *
     * List of time off scheduled..
     *
     */
    public function testGetTimeoffs()
    {
    }

    /**
     * Test case for updateTimeoff
     *
     * Update a time off's details.
     *
     */
    public function testUpdateTimeoff()
    {
    }
}
